### ISSUE TITLE
Any specific way to follow for composer packages?

### ISSUE THREAD

**Issue by KeremArdicli** [frozeeen/PHP-file-based-routing#1]
Should we include vendor/autoload.php to bootstrap.php ?

**Comment by frozeeen** [comment]
Hi @KeremArdicli, thank you looking into this.

Yes, I believe we can use the bootstrap or the index file in the current structure.
What do you think?

**Comment by KeremArdicli** [comment]
I would choose bootstrap i guess. I just downloaded the package today, and it seems i like it a lot. I may have more experience in the days ahead,  hence more recommendations. As a php package manager, I assume coming with a default solution for composer packages is a must. And we can define more options in the configuration file, I assume.

**Comment by frozeeen** [comment]
Glad to know! Thanks @KeremArdicli!
Feel free.

**Comment by KeremArdicli** [comment]
@frozeeen one more question. In nested folders, if there is extra middleware in a nested folder, the parent one is disregarded. Am I right? Can we or shall we make it so the main middleware is regarded as well?

**Comment by frozeeen** [comment]
You're right, the middleware outside is disregarded.

Can, we can make it to have an array of middleware, but my thought is that certain middleware can be coupled to other pages. If we have logging middleware in the root, it'll also log everything.

other work around is, just include other middleware, for example, inside the:

```php
# /auth/nested/+middleware.php
require __DIR__ . "/../+middleware.php";
```

However, if it is really required to enforce additional middleware on its child, perhaps we can use a classifier such as, 
`+middleware.global.php` or something.

What do you think @KeremArdicli ?

**Comment by KeremArdicli** [comment]
I have come up with an idea of putting middlewares in an array and include all of them :) good old days.

```php
$middleware_files = [];

# Check for middlewares
if (file_exists($destination_path . DIRECTORY_SEPARATOR . $middleware_file_name)) {
$middleware_path = $destination_path . DIRECTORY_SEPARATOR . $middleware_file_name;
$middleware_files[] = $middleware_path;
}

# Check if a raw file exist
if (file_exists($moving_path . DIRECTORY_SEPARATOR . $middleware_file_name)) {
$middleware_path = $moving_path . DIRECTORY_SEPARATOR . $middleware_file_name;
$middleware_files[] = $middleware_path;
}

#|==================================
#| Run the Middleware
#|==================================
if ($middleware_path) {
	foreach ($middleware_files as  $value) {
		require_once $value;
	}
}
```

However, +middleware.global.php method is a lot better approach I presume. Especially if it can be applied in sub folders for their child folders.

**Comment by KeremArdicli** [comment]
@frozeeen 

There are couple of more subjects I want to discuss with you. Once applied, the structure will be very close to every day use, I believe.

1. Configuration directory
    - I have created a config folder in main directory. Added it into bootstrap. In this directory, I can store my DB connection and other configuration files. 
    - Beside ASSETS and ENTRY_FOLDER, I also defined ENTRY_URL which makes it more reliable for redirects.
    - With this approach, I believe we can also define .env variables and include them in the project whereever we need.
 
2.  Templates folder
    - I created a template folder in pages directory.  I blocked user access via .htaccess to that folder. 
    - I created a navbar in there as an example.
    - At first, I was using include_once for the template file in relevant middlewares. After that, I defined a variable in the bootstrap named `$navbar`. If it is set to true then it is included right before `require_once $destination_path;`. I used your `$is_not_found` solution. 
    - The more the templates, the bigger the hustle will be. Therefore, I think an array of templates, or an ENUM or Class or so could be useful to control template files and whether they will be included in certain files.
    - I am not sure of a clean implementation. I tend to put everything in one file and I neither like nor use OOP. :(
    
3. Authentication
    - I set up my own authentication but a ready to go system could be nice. 
    - For that I craeted a login folder under pages directory. Shall it be implemented in main index.get.php or what do you think?

4. User Access Control
    - It is a serious part of my web apps. Not every user has access to neither every page nor every api method. This has to be controlled somehow.
    - I have user_permissions and navigation tables in my sql. While logging in, I check all of those and set allowed routes and methods in a session varible. Then use this varible in bootstrap to either show the page or deny the request.
    - This approach worked like a charm until I craeted a slug directory and file. since slugged directories are not in the table, request was redirected to 404. I solved it with using str_starts_with check rather than == check.
    - I do not have extensive knowledge or experience in this matter. I believe you can come up with a better idea :) ın any case, my implementation is below:

```php
$allowed_paths = ["/", "logout", "login", ""]; #allowed paths for everyone

#|==================================
#| Check permission
#|==================================
if (isset($_GET['__url__']) && isset($_SESSION["menu_items"])) {
	$matching_items = array_filter($_SESSION["menu_items"], function ($menu_item) {
		return isset($menu_item['link']) && str_starts_with($_GET['__url__'], $menu_item['link']); #using str_starts_with to allow slugs
	});
}

if (!empty($matching_items)) {
    // Retrieve the first match's title
    $page_title = reset($matching_items)['title'];
    $is_not_found = false;
} else {
    $page_title = null; // Or any default value
    $is_not_found = true;
}

#|==================================
#| Check if the page is allowed for everyone
#|==================================
$url = $_GET['__url__'];
$results = array_map(function ($allowed_path) use ($url) {
    return str_starts_with($url, $allowed_path);
}, $allowed_paths);

$is_allowed = in_array(true, $results, true);
if (in_array($_GET['__url__'], $allowed_paths) || $is_allowed || !isset($_GET['__url__'])) {
	$is_not_found = false;
}
```

I am eagerly waiting your response and open to your suggestions and directives. 

Regards...

**Comment by frozeeen** [comment]
> I have come up with an idea of putting middlewares in an array and include all of them :) good old days.
> 
> ```
> $middleware_files = [];
> 
> # Check for middlewares
> if (file_exists($destination_path . DIRECTORY_SEPARATOR . $middleware_file_name)) {
> $middleware_path = $destination_path . DIRECTORY_SEPARATOR . $middleware_file_name;
> $middleware_files[] = $middleware_path;
> }
> 
> # Check if a raw file exist
> if (file_exists($moving_path . DIRECTORY_SEPARATOR . $middleware_file_name)) {
> $middleware_path = $moving_path . DIRECTORY_SEPARATOR . $middleware_file_name;
> $middleware_files[] = $middleware_path;
> }
>
> #|==================================
> #| Run the Middleware
> #|==================================
> if ($middleware_path) {
> 	foreach ($middleware_files as  $value) {
> 		require_once $value;
> 	}
> }
> ```
> 
> However, +middleware.global.php method is a lot better approach I presume. Especially if it can be applied in sub folders for the subber folders.

This is great! I believe a minor refactor can support the +middleware.global if we're going on that way.

**Comment by frozeeen** [comment]
**1. Configuration**
This is fine, thank you!

**2. Templates**
I'm not sure if I follow you here. Correct me if I'm wrong, I guess you're trying to create a shared components for pages?
If yes, for me we can create a `templates` folder outside, this will isolate the pages and just create a helper to load a component if really needed, for example.

```php
# index.php
<?php
    renderComponent("navigation");
?>
Some content here
```

So the structure will be like this:

```
pages
  - index.get.php
templates
  - nav.php
```

**3. Authentication**
Yes, a built-in authentication is nice to have, and the login page is really depends per dev/requirements.

**4. User Access Control**
This is cool, but I believe this permission is really depends how dev handle Access Control, and as far as I know they are handled mostly in the middleware. Please do expound if I misunderstood this one.

I do really appreciate you effort in this one, thank you @KeremArdicli .

**Comment by KeremArdicli** [comment]
@frozeeen 
You are most welcome. I do thank you for allowing me using routing without any framework dependency.

- Hope you update package with config folder and its implementation. If you like I can try sending a PR, yet I am not so familiar with such things :( .

- You got me completely true with templates. Taking it out of pages folder would be nicer I gather.

- I agree with authentication. If a dev wants to use Google OAuth for example, embedded solution would not be of help at all. Leaving it as is is the best approach.

- For User Access Control, I started controling things in the middleware files. It looked cumbersome to edit every single file with the same content. Then I told my self I can avoid repetition by putting it in the bootstrap. Maybe alienating it from bootstrap and putting in another file like auth.php and include_once it in bootstrap would be nicer. This is still a niche feature and may not have a place in a file-based-routing repo. I get it if you stay away from such implementations.

All aside, I really like where the package has come for me, and I will gladly introduce it in reddit or anywhere else.

Thanks again for your time and effort.

Cheers.

**Comment by frozeeen** [comment]
Yes! you can send a PR, and when yes, I'll implement other things we've discuss. Thank you!

I'm glad you liked this project, I do really appreciate it.

**Comment by KeremArdicli** [comment]
> Yes! you can send a PR, and when yes, I'll implement other things we've discuss. Thank you!

PR sent 👍
